version: '3.1'

services:
    mysql:
        image: mysql:latest
        container_name: mysql_container
        hostname: mysql
        ports:
            - 13306:3306
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
            MYSQL_DATABASE: spring_microservicios
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: mysql
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - lan
    redis:
        image: redis:6.0
        hostname: redis
        container_name: redis_server_container
        restart: always
        ports:
            - 6379:6379
        command: redis-server --appendonly yes --requirepass "mypass"
        networks:
            - lan
    users:
        image: spring/users_service:V1
        ports:
            - 18080:8080
        container_name: user_service_container
        restart: always
        links:
            - redis:redis
            - mysql:mysql
            - kafka:kafka
        depends_on:
            - mysql
            - redis
            - kafka
        networks:
            - lan
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
          - 2181:2181
        container_name: zookeeper_container
        networks:
            - lan
    kafka:
        image: wurstmeister/kafka
        container_name: kafka_container
        hostname: kafka
        ports:
          - 9092:9092
        environment:
          KAFKA_ADVERTISED_HOST_NAME: 192.168.0.5
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_MESSAGE_MAX_BYTES: 2000000
          KAFKA_CREATE_TOPICS: soadev-topic:5:1
        links:
          - zookeeper:zookeeper
        depends_on:
          - zookeeper
        networks:
            lan:
                ipv4_address: 192.168.0.5

networks:
    lan:
        driver: bridge
        ipam:
            config:
                - subnet: "192.168.0.0/24"
                  gateway: "192.168.0.1"

volumes:
    dbdata:
        driver: local
